# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import starburst.event_sources.grpc.protogen.job_submit_pb2 as job__submit__pb2


class JobSubmissionStub(object):
    """Interface exported by the starburst scheduler
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitJob = channel.unary_unary(
                '/starburst.JobSubmission/SubmitJob',
                request_serializer=job__submit__pb2.JobMessage.SerializeToString,
                response_deserializer=job__submit__pb2.JobAck.FromString,
                )


class JobSubmissionServicer(object):
    """Interface exported by the starburst scheduler
    """

    def SubmitJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobSubmissionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitJob,
                    request_deserializer=job__submit__pb2.JobMessage.FromString,
                    response_serializer=job__submit__pb2.JobAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'starburst.JobSubmission', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class JobSubmission(object):
    """Interface exported by the starburst scheduler
    """

    @staticmethod
    def SubmitJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/starburst.JobSubmission/SubmitJob',
            job__submit__pb2.JobMessage.SerializeToString,
            job__submit__pb2.JobAck.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
