# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: job_submit.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10job_submit.proto\x12\tstarburst\"\x1d\n\nJobMessage\x12\x0f\n\x07JobYAML\x18\x01 \x01(\t\"\x19\n\x06JobAck\x12\x0f\n\x07retcode\x18\x01 \x01(\x05\x32H\n\rJobSubmission\x12\x37\n\tSubmitJob\x12\x15.starburst.JobMessage\x1a\x11.starburst.JobAck\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'job_submit_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _JOBMESSAGE._serialized_start=31
  _JOBMESSAGE._serialized_end=60
  _JOBACK._serialized_start=62
  _JOBACK._serialized_end=87
  _JOBSUBMISSION._serialized_start=89
  _JOBSUBMISSION._serialized_end=161
# @@protoc_insertion_point(module_scope)
